---
name: Update doc example

on:
  push:
    tags:
      - v*
  workflow_dispatch: { }

jobs:
  push-docs:
    name: Update test doc in rewrite-docs
    runs-on: ubuntu-latest
    steps:
      # Test release
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Load SSH deploy-key
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.REWRITE_DOCS_DEPLOY_KEY }}

      # Push the test release to rewrite-docs
      - name: Push to rewrite-docs
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone git@github.com:openrewrite/rewrite-docs.git
          export tag=${{ github.ref_name }}
          printf "\n${tag#v}\n" >> test-doc.md
          cp test-doc.md rewrite-docs/test-doc.md
          cd rewrite-docs/
          git add --all && git commit --message "Mike-test with reference ${{ github.ref_name }}" && git push --set-upstream origin master
